functionsDirectory = "/Users/kimhyun/lumi.it/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/kimhyun/lumi.it"
publishOrigin = "config"
functions = "/Users/kimhyun/lumi.it/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.scheduled-trends]
schedule = "0 0 * * *"

[functions."*"]
node_bundler = "esbuild"